### ISSUE TITLE
can't run eunomia-exporter

### ISSUE THREAD

**Issue by wanqingYuan** [eunomia-bpf/eunomia-bpf#18]
按照说明编译了eunomia-bpf  ecli  , 但是编译eunomia-exporter 时 始终停留在 updating crates.io index 3.51% ,所以我中断编译后直接从releases中下载了eunomia-exporter , 并尝试运行，出现以下错误

<img width="586" alt="image" src="https://user-images.githubusercontent.com/61040457/189935996-4832f327-8361-476e-865d-20330814fe0b.png">

 刚开始我怀疑可能是opensnoop_package.json的原因，于是换了另一个package.json , 错误仍然存在

**Comment by yunwei37** [comment]
https://github.com/eunomia-bpf/eunomia-bpf/tree/master/eunomia-exporter

我更新了新的 README，也许你可以看看。这应该是配置文件路径有些问题，或者说 opensnoop_package.json 就不是给 config.yaml 准备的。我已经更新了名称，它是给 curl post 用的 example，API 也修好了

**Comment by yunwei37** [comment]
https://eunomia-bpf.github.io/eunomia-bpf/opensnoop/package.json 可以使用预编译好的 package.json

config.yaml 是这样：


```yml
programs:
- name: opensnoop
  metrics:
    counters:
    - name: eunomia_file_open_counter
      description: test
      labels:
      - name: pid
      - name: comm
      - name: filename
        from: fname
  compiled_ebpf_filename: package.json
```
